name = "assemblyai"
version = "1.0.0"
target = "javascript"

description = "API client for assembly.ai API."
licences = ["Apache-2.0"]
repository = { type = "github", user = "iindyverse", repo = "assemblyai" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
midas = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.7.2 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 4.0.0"
oas_generator_utils = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
oas_generator = ">= 2.3.0 and < 3.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
